// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: stock_sentiment/stock_sentiment.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StockSentimentClient is the client API for StockSentiment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockSentimentClient interface {
	// GetStockSentiments returns a batch of stocks and their sentiment scores.
	GetStockSentiments(ctx context.Context, in *RequestParams, opts ...grpc.CallOption) (*StockBatch, error)
}

type stockSentimentClient struct {
	cc grpc.ClientConnInterface
}

func NewStockSentimentClient(cc grpc.ClientConnInterface) StockSentimentClient {
	return &stockSentimentClient{cc}
}

func (c *stockSentimentClient) GetStockSentiments(ctx context.Context, in *RequestParams, opts ...grpc.CallOption) (*StockBatch, error) {
	out := new(StockBatch)
	err := c.cc.Invoke(ctx, "/StockSentiment/GetStockSentiments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockSentimentServer is the server API for StockSentiment service.
// All implementations must embed UnimplementedStockSentimentServer
// for forward compatibility
type StockSentimentServer interface {
	// GetStockSentiments returns a batch of stocks and their sentiment scores.
	GetStockSentiments(context.Context, *RequestParams) (*StockBatch, error)
	mustEmbedUnimplementedStockSentimentServer()
}

// UnimplementedStockSentimentServer must be embedded to have forward compatible implementations.
type UnimplementedStockSentimentServer struct {
}

func (UnimplementedStockSentimentServer) GetStockSentiments(context.Context, *RequestParams) (*StockBatch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockSentiments not implemented")
}
func (UnimplementedStockSentimentServer) mustEmbedUnimplementedStockSentimentServer() {}

// UnsafeStockSentimentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockSentimentServer will
// result in compilation errors.
type UnsafeStockSentimentServer interface {
	mustEmbedUnimplementedStockSentimentServer()
}

func RegisterStockSentimentServer(s grpc.ServiceRegistrar, srv StockSentimentServer) {
	s.RegisterService(&StockSentiment_ServiceDesc, srv)
}

func _StockSentiment_GetStockSentiments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockSentimentServer).GetStockSentiments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StockSentiment/GetStockSentiments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockSentimentServer).GetStockSentiments(ctx, req.(*RequestParams))
	}
	return interceptor(ctx, in, info, handler)
}

// StockSentiment_ServiceDesc is the grpc.ServiceDesc for StockSentiment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockSentiment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StockSentiment",
	HandlerType: (*StockSentimentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockSentiments",
			Handler:    _StockSentiment_GetStockSentiments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock_sentiment/stock_sentiment.proto",
}
